;#lang racket/base

(require rackunit)

(define dlist-tests
  (test-suite
    "Tests for the dlist"

    (test-case "Initial dlist Properties"
    (let ((dl (make-dlist)))
      (check-equal? (size dl) 0 "Dlist initially should have size zero.")
      (check-equal? (delete dl '()) null "")
      (check-equal? (size dl) 0 "")
      ))
    
    (test-case "One Element dlist --- Functional Test"
    (let ((dl (make-dlist)))
      (check-equal? (size dl) 0 "")
      (insert-front dl '10)
      (check-equal? (size dl) 1 "")
      (delete dl '10)
      (check-equal? (size dl) 0 "")
      (insert-back dl '10)
      (check-equal? (size dl) 1 "")
      (delete dl '10)
      (check-equal? (size dl) 0 "")
      (insert-ordered dl '10)
      (check-equal? (size dl) 1 "")
      (delete dl '10)
      (check-equal? (size dl) 0 "")
      ))
    
    (test-case "One Element dlist --- Internal Test"
    (let ((dl (make-dlist)))
      (check-equal? (size dl) 0 "")
      (insert-front dl '10)
      (check-equal? (size dl) 1 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) '10 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '10 "")
      (delete dl '10)
      (check-equal? (size dl) 0 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) 'sentinel "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) 'sentinel "")
      (insert-back dl '10)
      (check-equal? (size dl) 1 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '10 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '10 "")
      (delete dl '10)
      (check-equal? (size dl) 0 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) 'sentinel "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) 'sentinel "")
      (insert-ordered dl '10)
      (check-equal? (size dl) 1 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) '10 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '10 "")
      (delete dl '10)
      (check-equal? (size dl) 0 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) 'sentinel "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) 'sentinel "")
      ))
    
    (test-case "Multi-Element dlist --- Internal Test"
    (let ((dl (make-dlist)))
      (check-equal? (size dl) 0 "")
      (insert-front dl '10)
      (insert-front dl '20)
      (check-equal? (size dl) 2 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) '10 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '20 "")
      (delete dl '10)
      (delete dl '20)
      (check-equal? (size dl) 0 "")
      (insert-back dl '10)
      (insert-back dl '20)
      (check-equal? (size dl) 2 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) '20 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '10 "")
      (delete dl '10)
      (delete dl '20)
      (check-equal? (size dl) 0 "")
      (insert-ordered dl '10)
      (insert-ordered dl '20)
      (check-equal? (size dl) 2 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) '10 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '20 "")
      (dlist-reverse dl)
      (check-equal? (size dl) 2 "")
      (check-equal? (dnode-data (dnode-next (dlist-sentinel dl))) '20 "")
      (check-equal? (dnode-data (dnode-prev (dlist-sentinel dl))) '10 "")
      (delete dl '10)
      (delete dl '20)
      (check-equal? (size dl) 0 "")
      ))
))

